baseURL = "https://pajakbalikpapan.github.io/"
languageCode = "en-us"
title = "Pajak"
title2 = "Balikpapan"
publishDir = "docs"
relativeURLs ="true"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    desktop = "images/logo/logo.svg"
    desktop_height = "42px"
    alt = "Pajak Balikpapan"

  [params.homepage_meta_tags]
    meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_og_title = "Pajak Balikpapan"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.footer]
    copyright_text = 'Hugo <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'


[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  [[menu.tutup]]
      name = "Team"
      url = "/team/"
      weight = 2
  [[menu.tutup]]
      name = "Contact"
      url = "/contact/"
      weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 0

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 0
